language: cpp

# For C++11 support 
sudo: required
dist: trusty

compiler:
    - clang
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
    - sudo add-apt-repository --yes ppa:amarburg/opencv3
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential
    - sudo apt-get install -qq cmake
    - sudo apt-get install -qq qt59-meta-minimal
    - sudo apt-get install -qq qt59multimedia
    - sudo apt-get install -qq qt59charts-no-lgpl
    - sudo apr-get install -qq libopencv3-dev

script:
    - source /opt/qt59/bin/qt59-env.sh
    - cmake .
    - make
