language: cpp

# For C++11 support 
sudo: required
dist: trusty

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential
    - sudo apt-get install -qq cmake
    - sudo apt-get install -qq qmake
    - sudo apt-get install -qq libopencv-dev
    - sudo apt-get install -qq qt5-default

install:
    - git clone https://github.com/qt/qtcharts.git
    - cd qtcharts && qmake && make && make install && cd ..

script:
    - cmake .
    - make
