language: cpp

# For C++11 support 
sudo: required
dist: trusty

compiler:
    - clang
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
    - sudo add-apt-repository --yes ppa:lkoppel/opencv
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential
    - sudo apt-get install -qq cmake
    - sudo apt-get install -qq qt59-meta-minimal
    - sudo apt-get install -qq qt59base
    - sudo apt-get install -qq qt59multimedia
    - sudo apt-get install -qq qt59charts-no-lgpl
    - sudo apt-get install -qq opencv

before_script:
  - curl -sL https://github.com/Itseez/opencv/archive/3.0.0.zip > opencv.zip
  - unzip opencv.zip
  - cd opencv-3.0.0

  - mkdir build install
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=OFF -D CMAKE_INSTALL_PREFIX=$(pwd)/../install -D WITH_FFMPEG=OFF -D WITH_IPP=OFF ..
  - make -j4
  - make install

  - cd ../../

script:
    - source /opt/qt59/bin/qt59-env.sh
    - cmake .
    - make
